# Generated by Django 4.0 on 2021-12-25 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tshirtapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='details',
            new_name='qty',
        ),
        migrations.AddField(
            model_name='order',
            name='tshirt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='tshirtapp.tshirt'),
        ),
    ]
