# Generated by Django 4.0 on 2021-12-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tshirtapp', '0002_rename_details_order_qty_order_tshirt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.CharField(max_length=64),
        ),
    ]
