# Generated by Django 4.0 on 2021-12-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tshirtapp', '0004_tshirt_tshirtid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshirt',
            name='tshirtid',
            field=models.CharField(default='T1', max_length=64, unique=True),
        ),
    ]
